# Generated by Django 3.0.6 on 2020-11-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201112_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
