# Generated by Django 3.0.6 on 2020-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201202_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
    ]
