# Generated by Django 3.0.6 on 2020-12-07 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2020, 12, 6)),
        ),
    ]
