# Generated by Django 3.0.6 on 2020-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='ads_type',
            field=models.CharField(blank=True, choices=[('ALL', 'all'), ('RENT', 'rent'), ('SALE', 'sale')], default='ALL', max_length=150, null=True, verbose_name='Тип объявлений'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='max_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
