# Generated by Django 3.0.6 on 2020-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201124_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='ads_type',
            field=models.CharField(blank=True, choices=[('Сдам', 'Сдам'), ('Продам', 'Продам')], max_length=150, null=True, verbose_name='Тип объявлений'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='max_area',
            field=models.PositiveIntegerField(blank=True, default=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
