# Generated by Django 3.0.6 on 2020-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201128_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='coordinates',
            field=models.CharField(max_length=8000),
        ),
    ]
