# Generated by Django 3.0.6 on 2020-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201202_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='max_area',
            field=models.PositiveIntegerField(blank=True, default=10000000, null=True, verbose_name='Максимальная площадь, м2'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Минимальная площадь, м2'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название полигона'),
        ),
    ]
